services:
  alloy:
    image: grafana/alloy:latest
    user: "0:0"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy/data
    ports:
      - "12345:12345"
      - "12347:12347"
      - "6832:6832"
      - "55679:55679"
      - "9091:9091"
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental
    restart: always
    networks:
      - monitoring_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - alloy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - monitoring_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
    depends_on:
      - alloy
      - tempo
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - monitoring_network

  tempo:
    image: grafana/tempo:latest
    user: "root"
    ports:
      - 3200:3200   # tempo query frontend
      - 9095:9095   # tempo grpc
      - 14268:14268 # jaeger ingest
      - 4318:4318   # otlp http (primary for traces)
      - 4317:4317   # otlp grpc (keep for compatibility)
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    depends_on:
      - mimir
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3200/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - monitoring_network

  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/loki.yaml", "-config.expand-env=true"]
    user: "root"
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki.yaml:/etc/loki/loki.yaml
      - loki-data:/tmp/loki
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - monitoring_network

  mimir:
    image: grafana/mimir:latest
    command: ["-ingester.native-histograms-ingestion-enabled=true", "-config.file=/etc/mimir.yaml"]
    ports:
      - "9009:9009"
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
      - mimir-data:/tmp/mimir
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9009/ready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    restart: always
    networks:
      - monitoring_network

volumes:
  alloy-data:
  tempo-data:
  loki-data:
  mimir-data:

networks:
  monitoring_network:
    external: true
    name: monitoring_network