global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:3003']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3004']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3002']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']