services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./admin_password:/run/secrets/admin_password
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin_password
    ports:
      - "3001:3000"
    networks:
      - monitoring_network

networks:
  monitoring_network:
    external: true
    name: monitoring_network